apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore
  namespace: demo
spec:
  provider:
    vault:
      version: "v2"
      #server: "http://10.0.8.14:8200"
      server: "http://0a3223a7-9227-4cb2-b21d-df9f214d2f61-10-244-4-23-8200.papa.r.killercoda.com"
      path: "demo"
      auth:
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "host-cluster"
          # A required field containing the Vault Role to assume.
          role: "demo"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "default"
