apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore
  namespace: demo
spec:
  provider:
    vault:
      #server: "http://10.0.8.14:8200"
      server: "https://774315d3-49dd-4bdd-8dcd-3bf11f34a241-10-244-3-105-8200.papa.r.killercoda.com"
      path: "demo"
      version: "v2"
      auth:
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "host-cluster"
          # A required field containing the Vault Role to assume.
          role: "demo"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          serviceAccountRef:
            name: "default"
