apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo-vault
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com/
    targetRevision: 0.20.1
    helm:
      values: |-
        global:
          enabled: false
        injector:
          enabled: true
          authPath: auth/host-cluster
          #externalVaultAddr: http://10.0.8.14:8200
          externalVaultAddr: http://3da70bef-e65f-4104-97db-757106b1ac0f-10-244-6-32-8200.papa.r.killercoda.com
    server: https://kubernetes.default.svc
    namespace: vault
  ignoreDifferences:
  - group: "admissionregistration.k8s.io"
    kind: "MutatingWebhookConfiguration"
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
